#+title: data steward survey 2021
#+author: Ilja Kocken

* description
This is the code to generate a report for the survey we sent out in november 2021 as the team of data stewards.

The goals of the survey were:
1. establish the data literacy of the different departments
2. put open science on the agenda of researchers
3. find open science champions to learn from

* requirements
This document is written in [[https://www.gnu.org/software/emacs/][emacs']] [[https://orgmode.org/][org-mode]], and is a [[https://en.wikipedia.org/wiki/Literate_programming][literate programme]].

We use a recent (>4.0.0) version of R with many packages in the [[https://www.tidyverse.org/][tidyverse]], most importantly [[ggplot2.tidyverse.org/][ggplot2]].

The [[https://github.com/davidsjoberg/ggsankey][ggsankey]] development package is installed from github.

We also tried out [[https://github.com/corybrunson/ggalluvial][ggalluvial]], but did not like it as much as the sankey graphs.

We use [[https://github.com/elbersb/tidylog][tidylog ]]in some cases to make sure the transformations are doing what we hope they do. Commands that use this package are prepended with ~tidylog::.~

* files
- [[file:dat/]] is a directory that contains the survey data exported to csv. *NOTE*: we excluded this from this repository for privacy's sake!
- [[file:imgs/]] is a directory that contains all the output images. *NOTE*: this is also excluded from the repository!
- [[file:out/]] is a directory containing intermediate outputs, such as rds files. *NOTE*: this is also excluded!
- [[file:processing.org]] reads in the raw data and cleans it up
- [[file:report.org]] generates a report with the appropriate graphs for all the questions in the survey
